version: "3.9"

services:

  # Хостинг изображений
  hosting:
    image: "nginx:alpine"
    ports:
      - "8083:80"
    volumes:
      - type: bind
        source: ./images/www
        target: /usr/share/nginx/html

  # Прокси-превьювер
  proxy:
    image: "proxy-previewer"
    ports:
      - "8081:8081"