// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	preview "github.com/andrey-tushev/otus-go/project/internal/preview"
	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// Get provides a mock function with given fields: img
func (_m *Cache) Get(img preview.Image) *preview.Container {
	ret := _m.Called(img)

	var r0 *preview.Container
	if rf, ok := ret.Get(0).(func(preview.Image) *preview.Container); ok {
		r0 = rf(img)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*preview.Container)
		}
	}

	return r0
}

// Set provides a mock function with given fields: img, container
func (_m *Cache) Set(img preview.Image, container *preview.Container) {
	_m.Called(img, container)
}

type mockConstructorTestingTNewCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCache(t mockConstructorTestingTNewCache) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
